services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Bolt\:
    resource: '../Classes/*'

  B13\Bolt\TsConfig\Loader:
    public: true
    tags:
      - name: event.listener
        identifier: 'add-site-configuration'
        event: TYPO3\CMS\Core\Configuration\Event\ModifyLoadedPageTsConfigEvent

  B13\Bolt\TypoScript\Loader:
    public: true

  B13\Bolt\TypoScript\AddTypoScriptFromSiteExtensionEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'b13-bolt/add-typoscript-from-site-extension'
        # for v10 compat, optional since v11
        event: TYPO3\CMS\Core\TypoScript\IncludeTree\Event\AfterTemplatesHaveBeenDeterminedEvent
